"""create processed_mentions table

Revision ID: 535b22e2ba0b
Revises: deee9b1a7004
Create Date: 2026-06-10 17:01:01.586705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535b22e2ba0b'
down_revision: Union[str, Sequence[str], None] = 'deee9b1a7004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_mentions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('sentiment_label', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['raw_mentions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_mentions_brand'), 'processed_mentions', ['brand'], unique=False)
    op.create_index(op.f('ix_processed_mentions_id'), 'processed_mentions', ['id'], unique=False)
    op.create_index(op.f('ix_processed_mentions_sentiment_label'), 'processed_mentions', ['sentiment_label'], unique=False)
    op.create_index(op.f('ix_processed_mentions_source'), 'processed_mentions', ['source'], unique=False)
    op.create_index(op.f('ix_processed_mentions_source_id'), 'processed_mentions', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_mentions_source_id'), table_name='processed_mentions')
    op.drop_index(op.f('ix_processed_mentions_source'), table_name='processed_mentions')
    op.drop_index(op.f('ix_processed_mentions_sentiment_label'), table_name='processed_mentions')
    op.drop_index(op.f('ix_processed_mentions_id'), table_name='processed_mentions')
    op.drop_index(op.f('ix_processed_mentions_brand'), table_name='processed_mentions')
    op.drop_table('processed_mentions')
    # ### end Alembic commands ###
