"""add top_opportunity_json

Revision ID: 55104d50b4c9
Revises: 873a4f4fa20a
Create Date: 2026-06-12 17:43:04.092270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55104d50b4c9'
down_revision: Union[str, Sequence[str], None] = '873a4f4fa20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_insights', sa.Column('top_opportunity_summary', sa.Text(), nullable=True))
    op.add_column('executive_insights', sa.Column('top_opportunity_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executive_insights', 'top_opportunity_json')
    op.drop_column('executive_insights', 'top_opportunity_summary')
    # ### end Alembic commands ###
