"""add engagement_score

Revision ID: 873a4f4fa20a
Revises: a5eef131f250
Create Date: 2026-06-12 17:21:03.098627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873a4f4fa20a'
down_revision: Union[str, Sequence[str], None] = 'a5eef131f250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_mentions', sa.Column('engagement_score', sa.Integer(), nullable=True))
    op.add_column('raw_mentions', sa.Column('engagement_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_mentions', 'engagement_score')
    op.drop_column('processed_mentions', 'engagement_score')
    # ### end Alembic commands ###
