"""Add pipeline_runs and alerts_log tables

Revision ID: 8e05ab1b5e00
Revises: 6bdc608e6dee
Create Date: 2026-06-12 14:27:48.805766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e05ab1b5e00'
down_revision: Union[str, Sequence[str], None] = '6bdc608e6dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_log_alert_type'), 'alerts_log', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_log_brand'), 'alerts_log', ['brand'], unique=False)
    op.create_index(op.f('ix_alerts_log_id'), 'alerts_log', ['id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stage_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_stage_name'), 'pipeline_runs', ['stage_name'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_stage_name'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_alerts_log_id'), table_name='alerts_log')
    op.drop_index(op.f('ix_alerts_log_brand'), table_name='alerts_log')
    op.drop_index(op.f('ix_alerts_log_alert_type'), table_name='alerts_log')
    op.drop_table('alerts_log')
    # ### end Alembic commands ###
