"""Add executive_insights and generated_reports tables

Revision ID: a5eef131f250
Revises: 8e05ab1b5e00
Create Date: 2026-06-12 15:05:11.567571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5eef131f250'
down_revision: Union[str, Sequence[str], None] = '8e05ab1b5e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executive_insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('top_risk', sa.Text(), nullable=True),
    sa.Column('top_opportunity', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_insights_brand'), 'executive_insights', ['brand'], unique=False)
    op.create_index(op.f('ix_executive_insights_id'), 'executive_insights', ['id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_id'), 'generated_reports', ['id'], unique=False)
    op.create_index(op.f('ix_generated_reports_report_type'), 'generated_reports', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_reports_report_type'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_executive_insights_id'), table_name='executive_insights')
    op.drop_index(op.f('ix_executive_insights_brand'), table_name='executive_insights')
    op.drop_table('executive_insights')
    # ### end Alembic commands ###
