"""create raw_mentions table with external_id

Revision ID: deee9b1a7004
Revises: 
Create Date: 2026-06-10 11:53:42.389350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deee9b1a7004'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_mentions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_mentions_brand'), 'raw_mentions', ['brand'], unique=False)
    op.create_index(op.f('ix_raw_mentions_external_id'), 'raw_mentions', ['external_id'], unique=True)
    op.create_index(op.f('ix_raw_mentions_id'), 'raw_mentions', ['id'], unique=False)
    op.create_index(op.f('ix_raw_mentions_source'), 'raw_mentions', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_mentions_source'), table_name='raw_mentions')
    op.drop_index(op.f('ix_raw_mentions_id'), table_name='raw_mentions')
    op.drop_index(op.f('ix_raw_mentions_external_id'), table_name='raw_mentions')
    op.drop_index(op.f('ix_raw_mentions_brand'), table_name='raw_mentions')
    op.drop_table('raw_mentions')
    # ### end Alembic commands ###
